package com.zjg.dao.model;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table device
 */
public class DeviceDO {
    /**
     * Database Column Remarks:
     *   主键id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device.gmt_create
     *
     * @mbg.generated
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device.gmt_modified
     *
     * @mbg.generated
     */
    private Date gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device.device_id
     *
     * @mbg.generated
     */
    private String deviceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device.pos_id
     *
     * @mbg.generated
     */
    private String posId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device.auth_code
     *
     * @mbg.generated
     */
    private String authCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device.device_type
     *
     * @mbg.generated
     */
    private String deviceType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device.device_version
     *
     * @mbg.generated
     */
    private String deviceVersion;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device.id
     *
     * @return the value of device.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device.id
     *
     * @param id the value for device.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device.gmt_create
     *
     * @return the value of device.gmt_create
     *
     * @mbg.generated
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device.gmt_create
     *
     * @param gmtCreate the value for device.gmt_create
     *
     * @mbg.generated
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device.gmt_modified
     *
     * @return the value of device.gmt_modified
     *
     * @mbg.generated
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device.gmt_modified
     *
     * @param gmtModified the value for device.gmt_modified
     *
     * @mbg.generated
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device.device_id
     *
     * @return the value of device.device_id
     *
     * @mbg.generated
     */
    public String getDeviceId() {
        return deviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device.device_id
     *
     * @param deviceId the value for device.device_id
     *
     * @mbg.generated
     */
    public void setDeviceId(String deviceId) {
        this.deviceId = deviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device.pos_id
     *
     * @return the value of device.pos_id
     *
     * @mbg.generated
     */
    public String getPosId() {
        return posId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device.pos_id
     *
     * @param posId the value for device.pos_id
     *
     * @mbg.generated
     */
    public void setPosId(String posId) {
        this.posId = posId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device.auth_code
     *
     * @return the value of device.auth_code
     *
     * @mbg.generated
     */
    public String getAuthCode() {
        return authCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device.auth_code
     *
     * @param authCode the value for device.auth_code
     *
     * @mbg.generated
     */
    public void setAuthCode(String authCode) {
        this.authCode = authCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device.device_type
     *
     * @return the value of device.device_type
     *
     * @mbg.generated
     */
    public String getDeviceType() {
        return deviceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device.device_type
     *
     * @param deviceType the value for device.device_type
     *
     * @mbg.generated
     */
    public void setDeviceType(String deviceType) {
        this.deviceType = deviceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device.device_version
     *
     * @return the value of device.device_version
     *
     * @mbg.generated
     */
    public String getDeviceVersion() {
        return deviceVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device.device_version
     *
     * @param deviceVersion the value for device.device_version
     *
     * @mbg.generated
     */
    public void setDeviceVersion(String deviceVersion) {
        this.deviceVersion = deviceVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", gmtCreate=").append(gmtCreate);
        sb.append(", gmtModified=").append(gmtModified);
        sb.append(", deviceId=").append(deviceId);
        sb.append(", posId=").append(posId);
        sb.append(", authCode=").append(authCode);
        sb.append(", deviceType=").append(deviceType);
        sb.append(", deviceVersion=").append(deviceVersion);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device
     *
     * @mbg.generated
     */
    public static DeviceDO.Builder builder() {
        return new DeviceDO.Builder();
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table device
     *
     * @mbg.generated
     */
    public static class Builder {
        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table device
         *
         * @mbg.generated
         */
        private DeviceDO obj;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table device
         *
         * @mbg.generated
         */
        public Builder() {
            this.obj = new DeviceDO();
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column device.id
         *
         * @param id the value for device.id
         *
         * @mbg.generated
         */
        public Builder id(Integer id) {
            obj.setId(id);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column device.gmt_create
         *
         * @param gmtCreate the value for device.gmt_create
         *
         * @mbg.generated
         */
        public Builder gmtCreate(Date gmtCreate) {
            obj.setGmtCreate(gmtCreate);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column device.gmt_modified
         *
         * @param gmtModified the value for device.gmt_modified
         *
         * @mbg.generated
         */
        public Builder gmtModified(Date gmtModified) {
            obj.setGmtModified(gmtModified);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column device.device_id
         *
         * @param deviceId the value for device.device_id
         *
         * @mbg.generated
         */
        public Builder deviceId(String deviceId) {
            obj.setDeviceId(deviceId);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column device.pos_id
         *
         * @param posId the value for device.pos_id
         *
         * @mbg.generated
         */
        public Builder posId(String posId) {
            obj.setPosId(posId);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column device.auth_code
         *
         * @param authCode the value for device.auth_code
         *
         * @mbg.generated
         */
        public Builder authCode(String authCode) {
            obj.setAuthCode(authCode);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column device.device_type
         *
         * @param deviceType the value for device.device_type
         *
         * @mbg.generated
         */
        public Builder deviceType(String deviceType) {
            obj.setDeviceType(deviceType);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column device.device_version
         *
         * @param deviceVersion the value for device.device_version
         *
         * @mbg.generated
         */
        public Builder deviceVersion(String deviceVersion) {
            obj.setDeviceVersion(deviceVersion);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table device
         *
         * @mbg.generated
         */
        public DeviceDO build() {
            return this.obj;
        }
    }
}