package com.zjg.dao.repository;

import com.zjg.dao.mapper.deviceDAO;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;

/**
 * This class was generated by MyBatis Generator
 * @author Thinkpad
 */
@Repository
public class deviceRepository {
    @Autowired
    private deviceDAO deviceDAO;
}