package com.zjg.dao.repository;

import com.zjg.dao.mapper.DeviceDAO;
import com.zjg.dao.model.DeviceDO;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;

/**
 * This class was generated by MyBatis Generator
 * @author Thinkpad
 */
@Repository
public class DeviceRepository {
    @Autowired
    private DeviceDAO deviceDAO;

    public void addDevice(DeviceDO deviceDO){
        deviceDAO.insert(deviceDO);
    }
}