package com.zjg.dao.mapper;

import com.zjg.dao.mapper.base.BaseBusinessDAO;
import org.apache.ibatis.annotations.Mapper;

/**
 * This class was generated by MyBatis Generator
 * @author Thinkpad
 */
@Mapper
public interface BusinessDAO extends BaseBusinessDAO {
}