package com.zjg.dao.mapper;

import com.zjg.dao.mapper.base.BasebusinessDAO;
import org.apache.ibatis.annotations.Mapper;

/**
 * This class was generated by MyBatis Generator
 * @author Thinkpad
 */
@Mapper
public interface businessDAO extends BasebusinessDAO {
}